### ISSUE TITLE
Microservices Tool Operation

### ISSUE THREAD

**Issue by anas-ce** [anas-ce/microservices-test-task#1]
Task 

-> Create a proto file for a microservice of ipinfo tool.
-> Generate the Grpc code from it.
-> Write a microservice server.py for this tool.
-> Test the microservice server with client side grpc code
-> Write a Router for this microservice which should handle input validation for any required input.
-> Deploy the router and microservice in separate containers and test them.

You can find necessary info regarding ipinfo and its free api key here : https://ipinfo.io/

**Comment by anas-ce** [comment]
Feedback:
-> Out of 6 points that I have listed, @hamza-CE has successfully completed 5.
-> The overall code structure and pattern is very good.
-> The documentation is also comprehensive.
-> However, docker configurations are not correct, the code works without it just fine on it not so much.

Overall Score: 5/6

-> We will discuss this feedback on Monday.

**Comment by hamza-CE** [comment]
fix the docker issue and pushed the final code with proper readme !!

**Comment by anas-ce** [comment]
Docker issue resolved, Closing Issue.

**Comment by anas-ce** [comment]
Docker issue resolved, Closing Issue.
